wandb_version: 1

exp_name:
  desc: null
  value: baseline
seeg_dir:
  desc: null
  value: /gpfs/data/tserre/Shared/Brainstorm_2024/seeg
video_dir:
  desc: null
  value: /gpfs/data/tserre/Shared/Brainstorm_2024/greenbook_videomae
lr:
  desc: null
  value: 1.0e-05
num_epochs:
  desc: null
  value: 20
ckpt:
  desc: null
  value: null
batch_size:
  desc: null
  value: 10
train_ratio:
  desc: null
  value: 0.7
model:
  desc: null
  value: orig
num_workers:
  desc: null
  value: 4
num_heads:
  desc: null
  value: 6
num_encoder_layers:
  desc: null
  value: 6
dim_feedforward:
  desc: null
  value: 2048
temperature:
  desc: null
  value: 0.07
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709603695.338889
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
