wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
alpha:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707275919.183587
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
